### ISSUE TITLE
[BUG] - missmatch btw container tag and python version

### ISSUE THREAD

**Issue by ant0n1s** [jupyter/docker-stacks#1742]
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

Ubuntu 20.04

### What Docker command are you running?

docker build fails

### How to Reproduce the problem?

build as base image with the version jupyter/minimal-notebook:python-3.9.12 works fine and fails with version jupyter/minimal-notebook:python-3.9.13

### Expected behavior

In line 18 of dockerfile you use python 3.10, but the tag suggests using of python version 3.9 as jupyter/minimal-notebook:python-3.9.13

https://hub.docker.com/layers/minimal-notebook/jupyter/minimal-notebook/python-3.9.13/images/sha256-702125eb8fb0a6e20d55fc7314fba6421708060e37a7d67dee8bee0a5c1951ca?context=explore

### Actual behavior

build fails due to python version missmatch.

**Comment by mathbunnyru** [comment]
Hello, @ant0n1s!

The image you are referring to, was built a month ago.
Unfortunately, we had an issue for a long time when instead of building image based on a freshly built image, we ended up using old parent image from DockerHub.
This issue was resolved just a few days ago, but we can't change old images, that's why their tags will always be incorrect.

I'm closing this issue, because we can't fix it, sorry for that.

**Comment by KaivnD** [comment]
Same here, I thought that's my problem, so I try restart my machine, reinstall docker, when I reinstall my windows, still the same. Finaly end up here, wow, move to jupyter/minimal-notebook:python-3.9.12, problem solved!
